Repository Kritika30032002/Blog_Website, pull requests merged in 2023-12, with the labels that each got.

#61 Issue:UI Enhacement: Hover effect for navbar links #40
  .env.example
  public/css/styles.css
  views/partials/header.ejs
Labels: Codepeak23, easy

#62 dark mode feature added.
  public/css/styles.css
  views/contact.ejs
  views/home.ejs
  views/partials/footer.ejs
  views/partials/header.ejs
  views/signin.ejs
  views/signup.ejs
Labels: Codepeak23, hard

#86 Update compose.ejs and and Ck Text Editor
  views/compose.ejs
Labels: Codepeak23, easy

#89 Added validation,notification and extra features
  app.js
  blog.json
  controllers/auth.js
  routers/auth.js
  views/blogs.ejs
  views/error.ejs
  views/home.ejs
  views/home2.ejs
  views/signin.ejs
  views/signup.ejs
Labels: Codepeak23, BONUS
